django_site/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('first_app/', include('first_app.urls'))
]

first_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="first_app"
urlpatterns = [
    path('', views.index),
    path('products/', views.products),
    path('products/<int:id>/', views.product_detail, name="product_detail")
]

first_app/models.py
from django.db import models

class Product(models.Model):
    def __str__(self):
        return self.name
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    desc = models.CharField(max_length=200)

first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Product

def index(request):
    return HttpResponse("Hello World")

def products(request):
    products = Product.objects.all()
    context = {
        "products": products
    }
    return render(request, 'first_app/index.html', context)

def product_detail(request, id):
    product = Product.objects.get(id=id)
    context = {
        "product": product
    }
    return render(request, 'first_app/detail.html', context)

first_app/templates/first_app/detail.html
This is the detail page
<h1>{{product.name}}</h1>
<h2>{{product.price}}</h2>
<p>{{product.desc}}</p>

first_app/templates/first_app/index.html
<html>
  <head></head>
  <body>
    <h1>This is a template</h1>
    {% for product in products %}
    <a href="{% url 'first_app:product_detail' product.id %}"
      >{{product.name}} - {{product.price}} - {{product.desc}}
    </a>
    <br />
    {% endfor %}
  </body>
</html>